FROM nvidia/cuda:11.6.1-devel-ubuntu20.04
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# Install basics
RUN apt update
RUN apt install -y wget git ffmpeg libsm6 libxext6 

ENV CONDA_DIR /opt/conda

# RUN wget --quiet https://repo.anaconda.com/archive/Anaconda3-2021.11-Linux-x86_64.sh && \
#     /bin/bash ./Anaconda3-2021.11-Linux-x86_64.sh -b -p /opt/conda && \
#     rm ./Anaconda3-2021.11-Linux-x86_64.sh 

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-py39_4.12.0-Linux-x86_64.sh && \
    bash Miniconda3-py39_4.12.0-Linux-x86_64.sh -b -p /opt/conda && \
    rm Miniconda3-py39_4.12.0-Linux-x86_64.sh

ENV PATH="/opt/conda/bin:$PATH"
# COPY environment.yml .
# RUN conda install -y -c conda-forge mamba
# RUN mamba env update -n base -f environment.yml
# RUN conda clean -afy
# RUN conda install -y -c conda-forge tensorflow=2.6.0 python=3.9
RUN conda install -y -c conda-forge python=3.9 && conda clean -afy
RUN pip install torch==1.13.1+cu116 torchvision==0.14.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116
RUN pip install torch-scatter -f https://data.pyg.org/whl/torch-1.13.0+cu116.html
RUN pip install hydra-core numba 
RUN pip install spconv-cu116
RUN pip install opencv-python
RUN pip install nuscenes-devkit
RUN pip install protobuf==3.20.*
# RUN pip install --no-cache-dir tensorflow==2.6.0
# RUN conda install -y -c conda-forge tensorflow==2.6.0
# RUN pip install waymo-open-dataset-tf-2-6-0